import { DoctorModel } from "@/models/doctor";
import { ServiceType } from "@/enums/service-type";
import sara from "@/assests/doctors-images/sara.jpg";
import john from "@/assests/doctors-images/john.jpg";
import mary from "@/assests/doctors-images/mary.jpg";
import jack from "@/assests/doctors-images/jack.png";

export const doctors: DoctorModel[] = [
  {
    id: "97420f0d-b576-4f65-9ffc-a81b4b1b4e77",
    name: "Sara",
    serviceType: ServiceType.ONLINE,
    image: sara.src,
    rate: 4.99,
    totalVotes: 594,
    address: "Germany",
    firstAvailableAppointment: "Tomorrow",
    specialityId: "1",
    specialityName: "Gynecologist",
    description:
      "Diagnosing and treating conditions of the female reproductive system",
  },
  {
    id: "88820f0d-b576-9ffc-a81b4b1b4e7",
    name: "John",
    serviceType: ServiceType.IN_PERSON,
    image: john.src,
    rate: 4.99,
    totalVotes: 294,
    address: "Netherlands",
    firstAvailableAppointment: "Next month",
    specialityId: "2",
    specialityName: "Cardiologist",
    description: "Expert in the care of your heart and blood vessels",
  },
  {
    id: "88820f0d-b576-335-9ffc-a81b1b4e7",
    name: "Mary",
    serviceType: ServiceType.ONLINE,
    image: mary.src,
    rate: 4.99,
    totalVotes: 894,
    address: "England",
    firstAvailableAppointment: "Next week",
    specialityId: "3",
    specialityName: "Neonatologist",
    description: "caring for newborn and premature babies",
  },
  {
    id: "8882000f0d-b576-335-9ffc-a81b4b1b4e7",
    name: "Jack",
    serviceType: ServiceType.IN_PERSON,
    image: jack.src,
    rate: 4.99,
    totalVotes: 2014,
    address: "Belgian",
    firstAvailableAppointment: "Next month",
    specialityId: "4",
    specialityName: "Pulmonologist ",
    description:
      "Diagnosing and treating diseases of the respiratory system, including airways, alveoli and blood vessels",
  },
  {
    id: "97420f0d-b576-4f65-fc-a81b4b1b4e77",
    name: "Sara",
    serviceType: ServiceType.IN_PERSON,
    image: sara.src,
    rate: 4.99,
    totalVotes: 594,
    address: "Germany",
    firstAvailableAppointment: "Tomorrow",
    specialityId: "5",
    specialityName: "Gastroenterologist",
    description:
      "Diagnosing and treating conditions of the female reproductive system",
  },
  {
    id: "88820f0d-76-9ffc-a81b4b1b4e7",
    name: "John",
    serviceType: ServiceType.ONLINE,
    image: john.src,
    rate: 4.99,
    totalVotes: 294,
    address: "Netherlands",
    firstAvailableAppointment: "Next month",
    specialityId: "6",
    specialityName: "Cosmetologist",
    description: "Expert in the care of your heart and blood vessels",
  },
  {
    id: "88820f0d-b576-335ffc-a81b1b4e7",
    name: "Mary",
    serviceType: ServiceType.IN_PERSON,
    image: mary.src,
    rate: 4.99,
    totalVotes: 894,
    address: "England",
    firstAvailableAppointment: "Next week",
    specialityId: "7",
    specialityName: "Dermatologist",
    description: "caring for newborn and premature babies",
  },
  {
    id: "8882000f-b576-335-9ffc-a81b4b1b4e7",
    name: "Jack",
    serviceType: ServiceType.ONLINE,
    image: jack.src,
    rate: 4.99,
    totalVotes: 2014,
    address: "Belgian",
    firstAvailableAppointment: "Next month",
    specialityId: "1",
    specialityName: "Gynecologist ",
    description:
      "Diagnosing and treating diseases of the respiratory system, including airways, alveoli and blood vessels",
  },
];
